version: "3.8"

services:
  byemoney:
    container_name: byemoney_db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: byemoney
      POSTGRES_PASSWORD: byemoney
      POSTGRES_DB: byemoney
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
