import type { Metadata } from "next";
import { Archivo_Black, Space_Grotesk } from "next/font/google";
import 'react-day-picker/dist/style.css'
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/context/theme";

const archivoBlack = Archivo_Black({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-head",
  display: "swap",
});

const space = Space_Grotesk({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivoBlack.variable} ${space.variable} antialiased text-black font-bold`}
      >
        <Toaster richColors />
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
